### ISSUE TITLE
Deviare DB rebuilt error

### ISSUE THREAD

**Issue by nblog** [nektra/Deviare2#49]
I corrected.
../Deviare2-master/Database/HeaderBuilder/build32.bat  Line:20
rem CALL "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" x86
CALL "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" x86 8.1
can get it right 
[preprocessed32W.h](https://1drv.ms/u/s!At5vghbk6PuShwJd2ukvtlT9Ja7N) 
[compile32.log](https://1drv.ms/u/s!At5vghbk6PuShwVGSVBnUw4LY1Bb)
[preprocessed64W.h](https://1drv.ms/u/s!At5vghbk6PuShwPtvtJ390B17GSi) 
[compile64.log](https://1drv.ms/u/s!At5vghbk6PuShwRDmh9lNdv7fGUf)
but, i used "../Deviare2-master/Database/DbBuilder/build_db32.bat", error occurred.
[DbGenerator32.log](https://1drv.ms/u/s!At5vghbk6PuShwboBc1hi4bCf33W)
I hope I can get help.

**Comment by mxmauro** [comment]
The database generator uses GCCXML to parse header files and build the database.

But the compiler is old and does not recognize the sentence `enum : bool { __the_value = false };` included in one of the files in SDK 8.1.

Because GCCXML is deprecated, I recommend to create a custom header and include only the APIs and structures you need in your application and just compile that.

Regards,
Mauro.
